dist: bionic
sudo: required
os:
  - linux
language: minimal

env:
  global:
    - PROGRESS_TYPE=plain
    - SPRYKER_PHP_VERSION=7.3
    - SPRYKER_DB_ENGINE=PGSQL

cache:
  timeout: 3600
  directories:
    - $HOME/build/spryker/project/vendor
    - $HOME/build/spryker/project/node_modules
    - $HOME/build/spryker/project/frontend/assets

addons:
  hosts:
    - yves.de.demo-spryker.com
    - zed.de.demo-spryker.com
    - glue.de.demo-spryker.com
    - queue.demo-spryker.com
    - scheduler.demo-spryker.com
  apt:
    packages:
      - apache2-utils
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - openssl aes-256-cbc -K $encrypted_ffb7c676c1f2_key -iv $encrypted_ffb7c676c1f2_iv -in ci/id_rsa.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - cd ${TRAVIS_BUILD_DIR}/../
  - rm -rf project
  - git clone git@github.com:spryker/suite-nonsplit.git project
  - rm -rf project/docker
  - mv ${TRAVIS_BUILD_DIR} project/docker

matrix:
  fast_finish: true
  allow_failures: []
  include:
    - name: Demo boot test
      env: DEV_MODE=0
    - name: Dev boot test
      env: DEV_MODE=1

script:
  - cd /home/travis/build/spryker/project/
  - if [[ $DEV_MODE == 0 ]] ; then docker/sdk boot; fi
  - if [[ $DEV_MODE == 1 ]] ; then docker/sdk boot deploy.dev.yml; fi
  - chmod +x docker/ci/check_boot.sh
  - ./docker/ci/check_boot.sh

notifications:
  email: false

