dist: bionic
sudo: required
os:
  - linux
language: minimal

env:
  global:
    - PROGRESS_TYPE=plain
    - SPRYKER_PHP_VERSION=7.3
    - SPRYKER_DB_ENGINE=PGSQL
    - SPRYKER_TEST_IN_BROWSER=firefox
    - SPRYKER_CODECEPT_CONFIG=

cache:
  timeout: 3600
  directories:
    - /home/travis/build/spryker/project/vendor
    - /home/travis/build/spryker/project/node_modules
    - /home/travis/build/spryker/project/frontend/assets

addons:
  hosts:
    - yves.de.demo-spryker.com
    - zed.de.demo-spryker.com
    - glue.de.demo-spryker.com
    - queue.demo-spryker.com
    - scheduler.demo-spryker.com
  apt:
    packages:
      - apache2-utils
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - openssl aes-256-cbc -K $encrypted_ffb7c676c1f2_key -iv $encrypted_ffb7c676c1f2_iv -in ci/id_rsa.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - cd ${TRAVIS_BUILD_DIR}/../
  - rm -rf project
  - git clone git@github.com:spryker/suite-nonsplit.git project
  - rm -rf project/docker
  - mv ${TRAVIS_BUILD_DIR} project/docker

matrix:
  fast_finish: true
  allow_failures: []
  include:
    - name: Demo Zed Acceptance tests
      env:
        - TEST_GROUP=acceptance
        - DEV_MODE=0
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.acceptance.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest, Zed]\""
    - name: Demo Yves Acceptance tests
      env:
        - TEST_GROUP=acceptance
        - DEV_MODE=0
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.acceptance.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest, Yves]\""
    - name: Demo Functional tests
      env:
        - TEST_GROUP=functional
        - DEV_MODE=0
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.functional.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest]\" -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" exclusive":" [Api, Glue]\""
    - name: Demo Api tests
      env:
        - TEST_GROUP=api
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.api.yml -vvv"
        - DEV_MODE=0

    - name: Dev Zed Acceptance tests
      env:
        - TEST_GROUP=acceptance
        - DEV_MODE=1
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.acceptance.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest, Zed]\""
    - name: Dev Yves Acceptance tests
      env:
        - TEST_GROUP=acceptance
        - DEV_MODE=1
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.acceptance.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest, Yves]\""
    - name: Dev Functional tests
      env:
        - TEST_GROUP=functional
        - DEV_MODE=1
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.functional.yml -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" inclusive":" [PyzTest]\" -o \"extensions":" config":" \SprykerTest\Shared\Testify\Helper\SuiteFilterHelper":" exclusive":" [Api, Glue]\""
    - name: Dev Api tests
      env:
        - TEST_GROUP=api
        - SPRYKER_CODECEPT_CONFIG=" -c codeception.api.yml"
        - DEV_MODE=1

script:
  - cd /home/travis/build/spryker/project/
  - if [[ $DEV_MODE == 0 ]] ; then docker/sdk boot; fi
  - if [[ $DEV_MODE == 1 ]] ; then docker/sdk boot deploy.dev.yml; fi
  - docker/sdk up -t
  - chmod ugo+x docker/ci/service-health-check.sh
  - chmod ugo+x docker/ci/api-tests.sh
  - bash ./docker/ci/service-health-check.sh
  - if [[ $TEST_GROUP != 'api' ]] ; then docker/sdk codecept codecept run${SPRYKER_CODECEPT_CONFIG}; fi
  - if [[ $TEST_GROUP == 'api' ]] ; then ./docker/ci/api-tests.sh; fi

notifications:
  email: false

