dist: bionic
sudo: required
os:
  - linux
language: minimal

git:
  clone: false

env:
   global:
     - PROGRESS_TYPE=plain
     - SPRYKER_PHP_VERSION=7.3
     - SPRYKER_DB_ENGINE=PGSQL

cache:
  timeout: 60

addons:
  hosts:
    - yves.de.spryker.local
    - zed.de.spryker.local
    - glue.de.spryker.local
  apt:
    packages:
      - apache2-utils
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

matrix:
  fast_finish: true
  allow_failures: []
  include:
    - name: Demo boot test
      env: DEV_MODE=0
      script:
        - chmod +x ci/check_boot.sh
        - ./ci/check_boot.sh
    - name: Dev boot test
      env: DEV_MODE=1
      script:
        - chmod +x ci/check_boot.sh
        - ./ci/check_boot.sh
    - name: Demo Bash syntax check
      env: DEV_MODE=0
      script:
        - chmod +x ci/check_bash_syntax.sh
        - ./ci/check_bash_syntax.sh
    - name: Demo Bash syntax check
      env: DEV_MODE=1
      script:
        - chmod +x ci/check_bash_syntax.sh
        - ./ci/check_bash_syntax.sh
    - name: Docker / B2C Demoshop / PHP-7.3 Alpine / MariaDB / Functional
      git:
          clone: false
      branches:
        only:
          - master
          - /feature\/[a-z]+-\d+\/(master).+|feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master).+/
          - /(bugfix|hotfix|beta)\/.+/
      os: linux
      dist: bionic
      language: shell
      env:
        - PROGRESS_TYPE=plain
        - SPRYKER_PLATFORM_IMAGE=spryker/php:7.3-alpine3.12
        - TRAVIS=1
        - APPLICATION_ENV=ci.pgsql
        - SPRYKER_TESTING_ENABLED=1
        - APPLICATION_STORE=DE
        - PROJECT=suite
        - POSTGRES_PORT="5433"
      script:
        - git clone --depth=3 --branch=master https://github.com/spryker-shop/b2c-demo-shop.git spryker-shop/b2c-demo-shop
        - cd spryker-shop/b2c-demo-shop && git clone https://github.com/spryker/docker-sdk.git --single-branch --branch master ./docker
        - docker/sdk boot deploy.ci.functional.mariadb.yml -v
        - docker/sdk up -t -v
        - docker/sdk testing codecept run -c codeception.ci.functional.yml
      before_script: skip
      after_script: skip


before_script:
  - chmod +x sdk
  - if [[ $DEV_MODE == 0 ]] ; then ./sdk boot ci/deploy.yml; fi
  - if [[ $DEV_MODE == 1 ]] ; then ./sdk boot ci/deploy.dev.yml; fi

notifications:
  email: false
