{
 "title": "SRE - APM Top Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "aws_account_environment",
    "query": {
     "query": "label_values(up,aws_account_environment)"
    }
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": {
     "query": "label_values(up{aws_account_environment=~\"$aws_account_environment\"},aws_region)"
    }
   },
   {
    "name": "customer_name",
    "label": "Customer",
    "query": {
     "query": "label_values(up{aws_account_environment=~\"$aws_account_environment\", aws_region=~\"$aws_region\"}, customer_name)"
    }
   },
   {
    "name": "aws_account_id",
    "label": "AWS Account ID",
    "query": {
     "query": "label_values(up{aws_account_environment=~\"$aws_account_environment\", aws_region=~\"$aws_region\",customer_name=~\"$customer_name\"}, aws_account_id)"
    }
   },
   {
    "name": "aws_account_name",
    "label": "Project name",
    "query": {
     "query": "label_values(up{aws_account_environment=~\"$aws_account_environment\", aws_region=~\"$aws_region\",customer_name=~\"$customer_name\",aws_account_id=~\"$aws_account_id\"}, aws_account_name)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_spanmetrics_calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*traces_spanmetrics_calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_spanmetrics_duration_seconds_bucket{aws_account_name=~\"$aws_account_name\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,service_name)))",
     "legendFormat": "{{le}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (service_name) (rate(traces_spanmetrics_calls_total{aws_account_name=~\"$aws_account_name\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(rate(traces_spanmetrics_calls_total{aws_account_name=~\"$aws_account_name\",status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "span_names Level - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum(rate(traces_spanmetrics_calls_total{aws_account_name=~\"$aws_account_name\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name)) "
    },
    {
     "expr": "topk(7, sum(rate(traces_spanmetrics_calls_total{aws_account_name=~\"$aws_account_name\",status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name))"
    }
   ]
  },
  {
   "title": "span_name Level - Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_spanmetrics_duration_seconds_bucket{aws_account_name=~\"$aws_account_name\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,span_name)))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (span_name,service_name)(increase(traces_spanmetrics_duration_seconds_sum{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval]) / increase(traces_spanmetrics_duration_seconds_count{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(7,sum by (span_name,service_name)(increase(traces_spanmetrics_duration_seconds_sum{aws_account_name=~\"$aws_account_name\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval]) / increase(traces_spanmetrics_duration_seconds_count{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval])))",
     "legendFormat": "[{{service_name}}]  {{span_name}}"
    }
   ]
  }
 ]
}