name: Boot & syntax check & tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Boot test
            dev-mode: [0, 1]
            script: |
              chmod +x sdk
              if [[ $DEV_MODE == 0 ]] ; then ./sdk boot ci/deploy.yml; fi
              if [[ $DEV_MODE == 1 ]] ; then ./sdk boot ci/deploy.dev.yml; fi
              bash ./ci/check_boot.sh

          - name: Bash syntax check
            dev-mode: [0, 1]
            script: |
              chmod +x sdk
              if [[ $DEV_MODE == 0 ]] ; then ./sdk boot ci/deploy.yml; fi
              if [[ $DEV_MODE == 1 ]] ; then ./sdk boot ci/deploy.dev.yml; fi
              bash ./ci/check_bash_syntax.sh

          - name: Tests
            dev-mode: [0, 1]
            script: |
              chmod +x sdk
              if [[ $DEV_MODE == 0 ]] ; then ./sdk boot ci/deploy.yml; fi
              if [[ $DEV_MODE == 1 ]] ; then ./sdk boot ci/deploy.dev.yml; fi
              bash ./ci/tests.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup packages
        run: |
          sudo apt-get -y install \
            apache2-utils \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            pigz \
            software-properties-common

      - name: Run script
        env:
          DEV_MODE: ${{ matrix.dev-mode }}
        run: ${{ matrix.script }}
