name: Boot & syntax check & tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Deploy file builder tests
            php-version: 7.4
            script: |
              cd generator
              composer install
              vendor/bin/codecept run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup packages
        run: |
          sudo apt-get -y install \
            apache2-utils \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            pigz \
            software-properties-common

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
